openapi: 3.0.0
info:
  title: GPT Drive Assistant API
  version: "1.0"
servers:
  - url: https://gpt-drive-assistant.onrender.com
paths:
  /generate-ppt:
    post:
      summary: 生成PPT文件
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                project_name:
                  type: string
                client_name:
                  type: string
                contact:
                  type: string
                quote_number:
                  type: string
                quote_date:
                  type: string
      responses:
        "200":
          description: 返回PPT下载地址
          content:
            application/json:
              schema:
                type: object
                properties:
                  download_url:
                    type: string
  /folders/{folder_id}/list:
    get:
      summary: 获取指定Google Drive文件夹下的文件
      parameters:
        - in: path
          name: folder_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 文件列表
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    mimeType:
                      type: string
