
openapi: 3.0.1
info:
  title: GPT Drive Assistant API
  description: Generate confirmation PPT and list Google Drive folder files.
  version: 1.0.0
paths:
  /generate-ppt:
    post:
      summary: Generate a confirmation PPT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                project_name:
                  type: string
                client_name:
                  type: string
                contact:
                  type: string
                quote_number:
                  type: string
                quote_date:
                  type: string
      responses:
        '200':
          description: A download link to the generated PPT
  /folders/{folder_id}/list:
    get:
      summary: List files in a Google Drive folder
      parameters:
        - name: folder_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of files
