
openapi: 3.0.1
info:
  title: GPT Drive Assistant API
  version: '1.0'
paths:
  /generate-ppt:
    post:
      summary: Generate PPT confirmation letter
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                project_name:
                  type: string
                client_name:
                  type: string
                contact:
                  type: string
                quote_number:
                  type: string
                quote_date:
                  type: string
      responses:
        '200':
          description: Download URL
  /folders/{folder_id}/list:
    get:
      summary: List files in Google Drive folder
      parameters:
        - name: folder_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of files
