openapi: 3.0.0
info:
  title: GPT Drive Assistant
  version: 1.0.0
paths:
  /generate-ppt:
    post:
      summary: Generate a PowerPoint confirmation file based on project data
  /folders/{folderId}/list:
    get:
      summary: List all files in a folder
