openapi: 3.1.0
info:
  title: GPT Drive Assistant
  version: 1.0.0
  description: Generate PowerPoint confirmation slides and access Google Drive folders/files.
servers:
  - url: https://gpt-drive-assistant.onrender.com
paths:
  /:
    get:
      operationId: healthCheck
      summary: Check if backend is running
      responses:
        "200":
          description: Health OK
          content:
            text/plain:
              schema:
                type: string
  /.well-known/ai-plugin.json:
    get:
      operationId: pluginManifest
      summary: Get AI Plugin metadata
      responses:
        "200":
          description: AI Plugin Manifest
          content:
            application/json:
              schema:
                type: object
  /folders/{folderId}/list:
    get:
      operationId: listDriveFiles
      summary: List all files in Drive folder (recursive)
      parameters:
        - name: folderId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of files
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    mimeType:
                      type: string
