openapi: 3.1.0
info:
  title: GPT Drive Assistant
  version: 1.0.0
  description: Generate PowerPoint confirmation slides and access Google Drive folders/files.
servers:
  - url: https://gpt-drive-assistant.onrender.com

paths:
  /:
    get:
      operationId: healthCheck
      summary: Check if backend is running
      responses:
        "200":
          description: Health OK
          content:
            text/plain:
              schema:
                type: string

  /.well-known/ai-plugin.json:
    get:
      operationId: pluginManifest
      summary: Get AI Plugin metadata
      responses:
        "200":
          description: Plugin metadata
          content:
            application/json:
              schema:
                type: object

  /generate-ppt:
    post:
      operationId: generatePPT
      summary: Generate a PowerPoint confirmation file
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                project_name:
                  type: string
                client_name:
                  type: string
                quote_number:
                  type: string
                quote_date:
                  type: string
                contact:
                  type: string
      responses:
        "200":
          description: Download URL for generated PPT
          content:
            application/json:
              schema:
                type: object
                properties:
                  download_url:
                    type: string

  /download-ppt/{filename}:
    get:
      operationId: downloadPPT
      summary: Download generated PowerPoint file
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Download PPT file
          content:
            application/vnd.openxmlformats-officedocument.presentationml.presentation:
              schema:
                type: string
                format: binary

  /folders/{folderId}/list:
    get:
      operationId: listFolderFiles
      summary: List files in a Google Drive folder
      parameters:
        - name: folderId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Files list
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    mimeType:
                      type: string

  /folders/{folderId}/recursive-files:
    get:
      operationId: listRecursiveFiles
      summary: Recursively list all files (including subfolders)
      parameters:
        - name: folderId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: All files recursively
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    mimeType:
                      type: string
