openapi: 3.1.0
info:
  title: GPT Drive Assistant API
  version: 1.0.0
  description: List and download Google Drive files, generate PPT.
servers:
  - url: https://gpt-drive-assistant.onrender.com
paths:
  /:
    get:
      summary: Health check
      operationId: healthCheck
      responses:
        "200":
          description: Running

  /.well-known/ai-plugin.json:
    get:
      summary: Serve ai-plugin manifest
      operationId: getManifest
      responses:
        "200":
          description: Manifest file
          content:
            application/json:
              schema:
                type: object

  /folders/{folderId}/list:
    get:
      summary: Recursively list all files in a Drive folder
      operationId: listAllFiles
      parameters:
        - name: folderId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: File metadata
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    mimeType:
                      type: string

  /generate-ppt:
    post:
      summary: Generate confirmation PowerPoint
      operationId: generatePPT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                project_name:
                  type: string
                client_name:
                  type: string
                quote_number:
                  type: string
                quote_date:
                  type: string
                contact:
                  type: string
      responses:
        "200":
          description: Download URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  download_url:
                    type: string
